# Generated by Django 3.2.9 on 2022-06-09 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='supervisor',
        ),
    ]
