# Generated by Django 3.2.9 on 2022-05-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20220524_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('', '------------'), ('undergraduate', 'Undergraduate'), ('postgraduate_masters', 'Post Graduate - Masters'), ('postgraduate_doctorate', 'Post Graduate - Doctorate'), ('postgraduate_professor', 'Post Graduate - Professor')], max_length=100),
        ),
    ]
