# Generated by Django 3.2.9 on 2022-05-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user_id',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
