# Generated by Django 3.2.9 on 2022-06-08 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervisors', '0001_initial'),
        ('students', '0006_student_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='supervisor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='supervisors.supervisor'),
        ),
    ]
