# Generated by Django 3.2.9 on 2022-05-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticate',
            name='access_level',
            field=models.CharField(blank=True, choices=[('', '------------'), ('Admin', 'Admin'), ('Supervisor', 'Supervisor'), ('Student', 'Student')], default=None, max_length=100, null=True),
        ),
    ]
