# Generated by Django 3.2.9 on 2022-05-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_authenticate_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticate',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
