# Generated by Django 3.2.9 on 2022-07-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_cabinet_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
