# Generated by Django 3.2.9 on 2022-06-09 11:46

import cabinet.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervisors', '0003_supervisor_supervisor_id'),
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalCabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(default='', max_length=30)),
                ('cabinet', models.CharField(blank=True, choices=[('', '------------'), ('undergraduate_dissertation', 'Undergraduate Dissertation'), ('masters_thesis', 'Masters Thesis'), ('phd_thesis', 'PHD Thesis'), ('professor_thesis', 'Professor Thesis'), ('research', 'Research')], default='no', max_length=100)),
                ('dapartment', models.CharField(blank=True, choices=[('', '------------'), ('information_systems', 'Information Systems'), ('computer_science', 'Computer Science'), ('business_studies_and_computing_science', 'Business Studies And Computing Science'), ('accounting', 'Accounting')], default='no', max_length=100)),
                ('document', models.FileField(upload_to=cabinet.models.ProposalCabinet.create_unique_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'jpg', 'png', 'jpeg', 'doc', 'xlsx'])])),
                ('notes', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('user_name', models.CharField(default=None, max_length=100)),
                ('created_at', models.DateField(default=None)),
                ('updated_at', models.DateField(default=None)),
                ('created_by', models.CharField(default=None, max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='cabinet',
            name='date',
        ),
        migrations.AddField(
            model_name='cabinet',
            name='reviewer_notes',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='status',
            field=models.CharField(blank=True, choices=[('', '------------'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='no', max_length=100),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='supervisor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='supervisors.supervisor'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='user_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='cabinet',
            field=models.CharField(blank=True, choices=[('', '------------'), ('undergraduate_dissertation', 'Undergraduate Dissertation'), ('masters_thesis', 'Masters Thesis'), ('phd_thesis', 'PHD Thesis'), ('professor_thesis', 'Professor Thesis'), ('research', 'Research')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='created_by',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='document_type',
            field=models.CharField(blank=True, choices=[('', '------------'), ('proposal', 'Proposal'), ('chapter_1', 'Chapter 1'), ('chapter_2', 'Chapter 2'), ('chapter_3', 'Chapter 3'), ('chapter_4', 'Chapter 4'), ('chapter_5', 'Chapter 5'), ('chapter_6', 'Chapter 6'), ('chapter_7', 'Chapter 7'), ('final_document', 'Final Document')], default='no', max_length=100),
        ),
    ]
