# Generated by Django 3.2.9 on 2022-05-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='document_type',
            field=models.CharField(blank=True, choices=[('', '------------'), ('undergraduate_dissertation', 'Undergraduate Dissertation'), ('masters_thesis', 'Masters Thesis'), ('phd_thesis', 'PHD Thesis'), ('professor_thesis', 'Professor Thesis'), ('research', 'Research')], default='no', max_length=100),
        ),
    ]
