# Generated by Django 3.2.9 on 2022-05-09 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('cabinet', '0002_alter_cabinet_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
