# Generated by Django 3.2.9 on 2022-05-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_cabinet_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='cabinet',
            field=models.CharField(blank=True, choices=[('', '------------'), ('undergraduate_dissertation', 'Undergraduate Dissertation'), ('masters_thesis', 'Masters Thesis'), ('phd_thesis', 'PHD Thesis'), ('professor_thesis', 'Professor Thesis'), ('research', 'Research')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='created_by',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='document_type',
            field=models.CharField(blank=True, choices=[('', '------------'), ('chapter_1', 'Chapter 1'), ('chapter_2', 'Chapter 2'), ('chapter_3', 'Chapter 3'), ('chapter_4', 'Chapter 4'), ('chapter_5', 'Chapter 5'), ('chapter_6', 'Chapter 6'), ('chapter_7', 'Chapter 7'), ('final_document', 'Final Document')], default='no', max_length=100),
        ),
    ]
