# Generated by Django 3.2.9 on 2022-05-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0004_auto_20220524_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinet',
            name='date',
        ),
    ]
