# Generated by Django 3.2.9 on 2022-05-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0006_remove_cabinet_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='user_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
