# Generated by Django 3.2.9 on 2022-06-09 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='supervisor_id',
        ),
    ]
